### PR TITLE
add possibility to have an other Login Url than the default one

### PR DESCRIPTION
**Pull request by unco182**
For a project I work for, I need to call a Url that look like `"https://\(loginHost)/services/oauth2/authorize/foo/bar`.

By adding this bit of code, it become possible.

Let me know if you want me to make any adjustments on this. Or if you find it irrelevant ! 

Cheers !

### CODE REVIEW

**Comment by mike4aday** [comment]
Thanks @unco182. Reviewing.

**Comment by mike4aday** [comment]
@unco182 what is the use case for adding extra path to the OAuth `authorization` endpoint? Have you seen issue #3 which discusses adding custom query string variables? Do you require additional path values, or would query string params work?

**Comment by unco182** [comment]
I'm working on a project where the Auth URL is https://\(loginHost)/services/oauth2/authorize**/yoloPath** so yes I need additional path value et already saw issue #3 
That's why I added this extra param to the initializer

**Comment by unco182** [comment]
I don't really get what do you want me to say about it. 

The use case is pretty simple, if your client want to use an other endpoint than the OAuth default endpoint, adding an extra path can be useful. (It just happened for the project i'm working for and that's why I added this extraUrl parameter).

**Comment by mike4aday** [comment]
@unco182 why would a client want to use an endpoint with extra path info? For example, additional query string parameters might be useful for Communities authentication. What use case does extra path info serve?

**Comment by mike4aday** [comment]
@unco182 I'm close to releasing version 7 and I will incorporate a fully-configurable login URL, very much in line with what you propose, and which will allow adding extra path info. So I think we shouldn't include this pull request in version 6 as it's a breaking change, though not major enough to warrant a full version jump. Thanks

**Comment by unco182** [comment]
Alright !

**Pull request closed without merging**
