### PR TITLE
Adding the choice to show - or not - the login view after logging out

### PR DESCRIPTION
**Pull request by victor-yn**
Adding a boolean showLoginView when logging out to give the user the choice of showing the login view or not after the logout process.

### CODE REVIEW

**Comment by ahbo** [comment]
This will help for a better user experience in apps...

**Comment by mike4aday** [comment]
@ahbo Thank you for the pull request. A couple things:
* As of version 6.0.4, you can call `ConnectedApp.revoke()` which will, effectively, do the same thing, i.e. attempt to invalidate the locally-stored token, and remove it from the keychain, and without displaying the login view afterwards.
* You could also implement your own `LoginDelegate` and customize the behavior. `logout()` was meant to be a convenience method when the `AppDelegate` also serves as the `LoginDelegate`.
Would either of these meet your needs?

**Comment by victor-yn** [comment]
@mike4aday Thank you for the clarifying that,  `ConnectedApp.revoke()` does indeed perfectly suits my needs. I did not realize that I was not on the lastest release (6.0.4). Thanks again.

**Comment by mike4aday** [comment]
Thank you for the feedback @victor-yn

**Pull request closed without merging**
